### ISSUE TITLE
problem 8 

### ISSUE THREAD

**Issue by RoelofWobben** [PEZ/rich4clojure#3]
I f I look at problem 8 I see this error in calva 

Unresolved namespace clojure.set. Are you missing a require?

on this line : 

 __ := (clojure.set/union #{:c :b :a} #{:c :b :d}))

**Comment by vettukal** [comment]
It shows the same for me, but the tests do run successfully.

**Comment by RoelofWobben** [comment]
yep, that is also true

**Comment by seancorfield** [comment]
That's just a warning from clj-kondo because `clojure.set` is referenced without being `:require`d in the `ns` form. It works because `clojure.set` is one of a handful of namespaces, other than `clojure.core`, that is "always" loaded by the time you get a REPL up and running, but it would be better practice to explicitly list it in the `ns` form.

**Comment by PEZ** [comment]
I'll add the missing require. We don't want to promote the bad practice of assuming something else has loaded things for us. 😄
