### ISSUE TITLE
problem 36  : unknow symbols

### ISSUE THREAD

**Issue by RoelofWobben** [PEZ/rich4clojure#8]
Hello, 

Whatever you try the x , y and z keeps unknown symbols here 

```
(ns rich4clojure.elementary.problem-36
  (:require [hyperfiddle.rcf :refer [tests]]))

;; = Let it Be =
;; By 4Clojure user: amalloy
;; Difficulty: Elementary
;; Tags: [math syntax]
;; 
;; Can you bind x, y, and z so that these are all true?

(def __ [z 1 y 3 x 7])

(comment
  
  )

(tests
 10 := (let __ (+ x y))
 4 := (let __ (+ y z))
 1 := (let __ z))

;; Share your solution, and/or check how others did it:
;; https://gist.github.com/ed751b2bcfa34398e03ea9f77a4d12b6
```

**Comment by seancorfield** [comment]
This is another one of those 4clojure problems where the semantics of Clojure don't apply to solving it with a `def`. The 4clojure site used to read the forms directly (without evaluating them) and perform a string replacement.

In this case, instead of `(def __ ...)` you would have to directly replace the `__` in each of the tests (with the same binding vector).

Solving this on Calva's side would probably mean resorting to macros (to prevent evaluation of forms) but is likely to make many of the tests harder to try to solve via the REPL in the `comment` since you would no longer be dealing with straightforward evaluation of expressions.

**Comment by PEZ** [comment]
The user isn't even supposed to solve this using the def. I totally can see why it would seem so. I'm considering removing these problems, but hoping we can do something better than that.

Still, this is covered in the README. Maybe I could add a priming problem that reminds about the README and also practices the two modes of solving the problems.
